### ISSUE TITLE
RegExp

### ISSUE THREAD

**Issue by Ayc0** [wooorm/space-separated-tokens#6]
Hello 👋 

I was reading the source code of this library, and I was wondering: why did you choose to use the regex `/[ \t\n\r\f]+/g` instead of `/\s/g` (that already includes all form of whitespaces)?

See:
![image](https://user-images.githubusercontent.com/22725671/146605875-aaf6dd71-4f16-4215-b92f-e17cbd4239dd.png)

**Comment by wooorm** [comment]
HTML whitespace is different from JavaScript whitespace. This regex matches whitespace in HTML. That regex matches whitespace in JavaScript.
